### ISSUE TITLE
Nice bro

### ISSUE THREAD

**Issue by zhanghan177** [Takudzwa-Rusike/Takudzwa-Rusike.github.io#1]
So you gonna create your personal website then?

**Comment by Takudzwa-Rusike** [comment]
Lololol, nah this is for one of my friends! This is just the easiest way 2 c it!

**Comment by zhanghan177** [comment]
Don't waste it then. Use it 😄

**Comment by Takudzwa-Rusike** [comment]
I will I will! Just not yet haha
